### ISSUE TITLE
Unpublished entries?

### ISSUE THREAD

**Issue by ursbraem** [masugadesign/cp-filters-craft-cms#21]
Hi!
Is it possible to filter unpublished entries (so they have only drafts) as well?

PS: sorry, I deleted the formalities. It's such a general question

**Comment by benjaminkohl** [comment]
Sorry for the late reply on this one. I don't think there is currently a way to include drafts in the results. I'd have to look into that a bit because a lot of the underlying code pertaining to drafts underwent a lot of changes back in the Craft 3.5 - 3.7 days. And it could get kind of weird when people also filter by element status because I can recall "live" drafts (which are not truly live at all) being an issue I ran into with other development.

**Comment by ursbraem** [comment]
Yeah I understand. Thanks anyway! Best

**Comment by benjaminkohl** [comment]
We just released v2.1.0 which includes a checkbox on the entries view for including drafts in the results.
