### ISSUE TITLE
Integration with Craft Commerce

### ISSUE THREAD

**Issue by willbocc** [masugadesign/cp-filters-craft-cms#3]
**Is your feature request related to a problem? Please describe.**
Commerce store managers frequently request the ability to export orders with associated line items, shipping rules and tax rates. Craft's export lacks the key order information needed for store managers. However, if store managers could filter orders with this plugin it could help hugely with dispatch.

**Describe the solution you'd like**
Enable a filter on Craft Commerce orders by customer, date, products purchased, order status, shipping category, vat category, etc.

**Describe alternatives you've considered**
Shipstation is a third party solution for order fulfilment which works well.
I have also built simple .csv templates which store managers can download using twig templates.

**Comment by nitech** [comment]
My editors could really benefit from Craft Commerce support. Hoping you will consider developing support for products soon.

**Comment by willbocc** [comment]
@nitech I now build a .csv export template for most commerce projects. This allows users - with the right permission level - the ability to download a .csv for orders matching specific queries. Not ideal, but a fairly easy work around.

**Comment by nitech** [comment]
Thanks for the reply William. Any plans on implementing full filters for products though?

**Comment by AndrewMac** [comment]
Yep, sorry, this issue is a bit of a show-stopper. I just now trialled this, with a view to install for clients, but with no support for at least products and orders it's just going to be a big disappointment for them. So I'm going to have to give it a miss for now, but may reconsider if product support gets built in.

**Comment by ryanmasuga** [comment]
We talked about this at length and any type of "full" Craft Commerce support will probably not happen with CP Filters. This plugin is for filtering, and the commerce requests feel more like "reporting".

Commerce is different enough (under the hood) that we think a separate reporting plugin would make more sense, rather than trying to roll in a ton of code most people won't use. For example, Orders don't have Products; they have Line Items which aren't even elements, and Line Items don't relate directly to Products, but relate to Purchasables, which are also not elements - it's just a different ballgame. The kind of filtering you'd want with Commerce is far from basic element filtering.

For $900+, we feel commerce should have basic reporting capability, and we can't really make a business case to spend the time on it when we see potential sales/installs being quite few - and having to support that doesn't make sense for us either, as we try to avoid working with commerce sites ourselves.

"Never say never", but we think a different plugin would fill the gap.

**Comment by nitech** [comment]
Hey @ryanmasuga. Wise conclusion. 

I've been impressed and delighted while using Craft CMS and Craft Commerce. However, I've reached the outer limits of what this product is really designed to solve. 

I think you're right when you say Commerce should have this functionality out of the box. It should also have [faceted search](https://craftcms.stackexchange.com/questions/36307/how-to-create-a-faceted-search-facet-filter-in-craft-commerce) or at least a smooth integration with Algolia, [manual sorting of products](https://github.com/craftcms/commerce/issues/229), [nested entry type definition](https://github.com/craftcms/cms/issues/7527), [ability to override default assset paths](https://github.com/craftcms/cms/issues/7156), the list goes on. 

I am working on a B2B site with 4k+ products.

**Comment by ryanmasuga** [comment]
@nitech Personally I'm not sure who Craft Commerce is targeting. I would imagine any company that has enough money to pay a dev shop for a totally custom cart/shop setup would expect it to come with ecommerce "basics" such as faceted search, manual sorting, decent reporting, etc.

We don't have interest in using Craft Commerce on our projects, so our lack of motivation to work on a plugin for it would not serve anyone well.

**Comment by cakleimeier** [comment]
Filtering of Products and Orders has been implemented as of v1.2.0, see 236c8ac5ef8724b9e86f2a0455605027613a9f0a

**Comment by ryanmasuga** [comment]
CP Filters 1.2.0 added support for Craft Commerce Products and Orders.
